<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
$productManager = $objectManager->get('\Magento\Catalog\Model\Product');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$refid = 0;
if($_item->getCustom_design()){
    $refid = $_item->getCustom_design();
}
$productModel = $productManager->load($_item->getProductId());
$attr = $eavConfig->getAttribute('catalog_product', 'xe_is_template');
if(null === $attr->getId()) {
    $preDecoratedProduct = 0;
}else{
    $preDecoratedProduct = boolval($productModel->getData("xe_is_template"));
}
$simpleProduct = $productManager->loadByAttribute('sku', $_item->getSku());
?>
<script type="text/javascript">
require(['jquery'],function($){
    ul = "<?php echo $baseUrl;?>";
    var refids="";
    var progressSvg = ul+'xetool/assets/images/progress.svg';
    require(['jquery', 'jquery/ui'], function($){
        jQuery(".loading").html('<img src="'+progressSvg+'" alt="Loading" style="text-align: center; vertical-align: middle;" /> ');
        <?php
            if($refid){
        ?>
            var getPreviewUrl = ul+'xetool/api/v1/preview-images?custom_design_id='+<?php echo $refid; ?>+'&product_id='+<?php echo $simpleProduct->getId(); ?>;
            jQuery.get(getPreviewUrl, function(data, status){
                if(status == 'success'){
                    if(data != ''){
                        var jsonObj = data;
						 var size = new Array();		
						var elem1 = jQuery("#shopping-cart-table tbody tr td dd.variation-Size");
						var i = 0;
						elem1.each(function(ind) {							
							size[i] = jQuery(this).text();
							i++;						
						});
                        jQuery("a.product-item-photo").each(function(index) {
                            jQuery("a.product-item-photo").css('width', '100%');
                            jQuery(".action").css('display', 'inline');
                            var sid = jQuery(this).find("input").attr('rel');
                            var obj = jQuery(this);
                            if(sid!=undefined){
                                jQuery.each(jsonObj,function(key, val){
                                    var keyWithProductId = key+<?php echo $simpleProduct->getId();?>;
                                    if(keyWithProductId == sid && val.length>0){
                                        var count=0;
                                        var print_id= val[0].printid;
										var sizeId = size[index];
                                        var customSize = val[0].variableDecorationSize;
                                        var customUnit = val[0].variableDecorationUnit;

                                        jQuery(obj).find('.printid').val(print_id);
                                        if (val[0].display_edit == 0) {
                                            jQuery("a.edit" + sid).css('display', 'none');
                                        }
                                        if (val[0].nameAndNumber == 1) {
                                            jQuery("a.edit" + sid).css('display', 'none');
                                        }else{
											jQuery("a.info" + sid).css('display', 'none');
										}
										jQuery(obj).find('.sizeid').val(sizeId);
                                        jQuery.each(val,function(imgKey, imgObj){
                                            if(imgObj['customImageUrl'] != ''){
                                                count++;
                                                if(count==1){
                                                    jQuery(obj).find("img").remove();
                                                }
                                                var newElement = '<a href="javascript:void(0)" title="" class="product-image product-thumb customize-image" style="float:left;width:80px"><img src="'+imgObj['customImageUrl'][imgKey]+'" width="75" height="75" alt="" rel="'+"<?php echo $refid.$simpleProduct->getId(); ?>"+'" style="display:block;" class="previewimg"></a>';
                                                if(customSize){
                                                   newElement = newElement + '<span><b>Custom Size:</b> '+ customSize + ' ' +customUnit +'</span>';
                                                }
                                                jQuery(obj).append(newElement);
                                            }
                                        });
                                    }
                                });
                            }
                            jQuery("a.product-item-photo").parent().find('.loading').hide();
                            jQuery("a.product-item-photo").show();
                      });
                    }
                }
            });
        <?php }?>
		});
	});
    function myFunction(refid, id) {
        var print_id = document.getElementById(refid).value;
        var sizeId = document.getElementById("sizeid"+id).value;
        var refid =  refid;
        var url = '';
        var ischecklogin = "<?php echo $customerSession->getId()?> ";
        customer = ischecklogin.trim();
        if(ischecklogin>0)  customer = '&customer='+customer;
        else customer = '&customer=0';
        var storeId = 1;
        var store = '&store='+storeId;
        var productId = '&id='+<?php echo $_item->getProductId()?>+'&vid='+sizeId;
		var cartItem = '&cart_item_id='+id;
        var screenWidth = (window.innerWidth > 0) ? window.innerWidth : screen.width;
        if(screenWidth < 1024){
            url = ul+"xetool/index.html?dpid="+refid+customer+store+productId+cartItem;
        }else{
            url = ul+"imprint-next?dpid="+refid+customer+store+productId+cartItem;
        }   
        window.location = url;
    }
	function nameAndNumberInfo(refid, id){
		var ul = "<?php echo $baseUrl;?>";
		var url = ul+'xetool/api/index.php';
		jQuery.get(url + "?reqmethod=getNameAndNumberByRefId&refId=" + refid+"&pid="+id, function(data) { 
		   if(data.nameNumberData !=''){
				var div = "<div id='name-number' style='display:none;'><table ><thead><tr><th style='border: 2px solid #f6f6f6;'></th><th colspan='2' style='text-align: center;border: 2px solid #f6f6f6;'>Front</th><th colspan='2' style='text-align: center;border: 2px solid #f6f6f6;'>Back</th></tr> <tr><th style='border: 2px solid #f6f6f6;'>Size</th><th style='border: 2px solid #f6f6f6;'>Name</th><th style='border: 2px solid #f6f6f6;'>Number</th> <th style='border: 2px solid #f6f6f6;'>Name</th><th style='border: 2px solid #f6f6f6;'>Number</th></tr></thead><tbody>";
				jQuery.each(data.nameNumberData, function(i, result) {
					div += "<tr><td style='border: 2px solid #f6f6f6;'>"+result.size+"</td><td style='border: 2px solid #f6f6f6;'>"+result.front.name+"</td><td style='border: 2px solid #f6f6f6;'>"+result.front.number+"</td><td style='border: 2px solid #f6f6f6;'>"+result.back.name+"</td><td style='border: 2px solid #f6f6f6;'>"+result.back.number+"</td></tr>";
				});
				div += "</tbody></table></div>";
				var divData = jQuery('#name-number');
				if(divData.length) divData.remove();
				jQuery('body').append(div);
				addDiv();
			}
		});
	}
	function addDiv(){
		require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Name And Number Details',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#name-number'));
            $('#name-number').modal('openModal');   
        }
        );
	}	
</script>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <input type="hidden"  class="printid" id="<?php echo $refid ; ?>" rel="<?php echo $refid.$simpleProduct->getId(); ?>" value="" />
            <input type="hidden"  class="productId" id="<?php echo "sizeid".$this->getItem()->getId(); ?>" value="<?php  $_sku = $this->getItem()->getsku(); $productObject = $productManager->loadByAttribute('sku', $_item->getSku()); echo $productObject->getId(); ?>" />
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details" style="display: table-caption;">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <?php if($_option['label'] != 'line_item_separate'): ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <div class="truncated_full_value">
                            <dl class="item-options">
                                <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                            </dl>
                        </div>
                            <?php endif; ?>
                        </dd>
                         <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>
        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php echo $block->getUnitPriceHtml($_item); ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <?php if($refid){?>
                        <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                               name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                               value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                               type="number"
                               size="4"
                               title="<?= $block->escapeHtml(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"
                               disabled="disabled"/>
                    <?php }else{ ?>
                        <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                           name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                           value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                    <?php } ?>
                </div>
            </div>
        </td>
        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php if($_item->getPrice() == '0.0000'){
                       $price = number_format($_item->getCustomPrice(),2);
                       $qty = $block->getQty();
                       $subTotal = number_format($price*$qty,2);
                       echo '₹'. $subTotal;
                    }else{?>
                        <?= $block->getRowTotalHtml($_item) ?>
                <?php } ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions"> 
        <td colspan="100">
            <div class="actions-toolbar">
                <?php if($refid && !$preDecoratedProduct){?>
                    <a href="javascript:void(0)" class="edit<?php echo $refid; ?>" onclick="myFunction(<?php echo $refid; echo ','; echo $this->getItem()->getId(); ?>)" title="Edit item parameters">Redesign</a>
					<a id="showinfo" href="javascript:void(0)" class="info<?php echo $refid.$simpleProduct->getId(); ?>" onclick="nameAndNumberInfo(<?php echo $refid; echo ','; echo $simpleProduct->getId(); ?>)" title="item info">Info</a>
                <?php } ?>
                
				<?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
<style>
.price-including-tax, .price-excluding-tax {
    display: inline-block!important;
}
.cart.table-wrapper .col > .price {
	color: #656161;
}
.product-image-container {
    width: 100px!important;
}
</style>