<?php 
if($this->isCustomizeButton()) {
	$productData = $this->getProduct();
	if($productData->getXe_is_designer() == 1) {
		$productId = $productData->getId();
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$customerSession = $objectManager->get('Magento\Customer\Model\Session');
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		$baseUrl = $storeManager->getStore()->getBaseUrl();
		$storeId = $storeManager->getStore()->getStoreId();
		$disableCrtButton = $productData->getData('disable_addtocart');
		if ($productData->getTypeId() == 'configurable') {
			$simpleCollection = $productData->getTypeInstance()->getUsedProducts($productData);
			if(!empty($simpleCollection)){
				foreach($simpleCollection as $simple){
					$firstVariantId = $simple->getId();
				}
			}
		}else{
			$firstVariantId = $productId;
		}
		$preDecoId = ($productData->getTemplate_id()) ? $productData->getTemplate_id() : 0 ;
		$categoryIds = $productData->getCategoryIds();
		if($this->isCustomizeButton() && ($productData->getXe_is_designer()) == 1) { ?>
			<input type="button" name="customize" id="customize" class="action primary tocart" style="width:242px; line-height:2.2rem; padding:14px 17px; font-size: 1.8rem;" value="Customize" onclick="customizeProduct();"/>
		<?php } ?>
		<script type="text/javascript">
			var baseUrl = "<?php echo $baseUrl;?>";
			var storeId = "<?php echo $storeId;?>";
			var selectedVariantId = <?php echo $firstVariantId;?>;
			var preDecoId = '';
			// for template based product
			var productCat = "<?php echo implode(',', $categoryIds);?>";
			var pbti = 0;
			if(<?php echo $preDecoId;?>){
				preDecoId = '&dpid='+<?php echo $preDecoId;?>;
			}
			require(['jquery', 'jquery/ui'], function($){
			    jQuery('#customize').insertBefore('div.product-social-links');

				//Disable product option
				<?php if($disableCrtButton == 1){ ?>
					jQuery('#product-options-wrapper').hide();
				<?php } ?>

				// Get selected simple product id
				jQuery(".product-options-wrapper select[id^='attribute']").last().on('change', function() {
					setTimeout(function (){
						selectedVariantId = jQuery("input[name=selected_configurable_option]").val();
				     }, 500);
				});
				// for template based product
			  	if(productCat != ''){
			    	jQuery.get(baseUrl+"xetool/api/v1/template-products?prodcatID="+productCat,function(data){
			    		data = JSON.parse(data);
			    		jQuery.each(data, function(i, item) {
				      		if(item != false){
				        		pbti = 1;
				      		}
						});
					});
				}
		 	});
			
			function customizeProduct() {
				var url = '';
				var variantId = '';
				var store = '&store_id='+storeId;
				var qty = '&qty='+document.getElementById('qty').value;
			    var screenWidth = (window.innerWidth > 0) ? window.innerWidth : screen.width;
				//Check for mobile device
				variantId =  variantId+"&vid="+selectedVariantId;
				if (screenWidth < 1024){
					url = baseUrl+"xetool/index.html?id=<?php echo $productId;?>"+variantId+preDecoId+qty+"&pbti="+pbti+store;
				}else{
					url = baseUrl+"imprint-next?id=<?php echo $productId;?>"+variantId+preDecoId+qty+"&pbti="+pbti+store;
				}
				window.location.href = url;
			}
		</script>
	<?php } ?>
<?php } ?>